export const ORDER_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  ASSEMBLY: 'ASSEMBLY',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  IN_TRANSIT: 'IN_TRANSIT',
  RECEIVED: 'RECEIVED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];

export const ORDER_STATUS_LIST = Object.values(ORDER_STATUS);
